TheTitle: Matrix Poll
TheSubtitle: Create your custom poll easily!
GiveTitle: Give it a title
Title: Title
Desc: Desc
ReadDesc: Read the description
GiveOptionalDesc: An optional description
GiveDesc: Describe the poll
ChooseColumns: Choose your columns
ColumnEx1: 1st of January
ColumnEx2: 2nd of January
ColumnEx3: 3rd of January
AddOneColumn: Add one column
ChooseAvailAnsw: Choose the available answers
Yes: Yes
No: No
Maybe: Maybe
AddOneAnswer: Add one column value
CreatePoll: Create the poll
FieldRequireNonEmpty: This field is not allowed to be empty
FillThePoll: Please fill in the poll
YourName: Your name
Save: Save
YouCreated title@Text: Your new poll "#{title}" is now online!
