Default: &defaults
  database: MatrixPoll.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: MatrixPoll_test.sqlite3
  <<: *defaults

Staging:
  database: MatrixPoll_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: MatrixPoll_production.sqlite3
  poolsize: 100
  <<: *defaults
